name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cloning repo
      uses: actions/checkout@v4

    - name: Building image
      run: docker build -t mayoubo/titanciv:latest .

    - name: Docker login
      run: docker login -u mayoubo -p ${{ secrets.DOCKER_HUB_TOKEN}}

    - name: Docker push
      run: docker push mayoubo/titanciv:latest
